//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjusteIPA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPA()
        {
            this.Reclamaciones = new HashSet<Reclamaciones>();
        }
    
        public int NumeroIPA { get; set; }
        public string NombreIPA { get; set; }
        public string NumeroPCP { get; set; }
        public string NombrePCP { get; set; }
        public Nullable<System.DateTime> FechaEfectividad { get; set; }
        public Nullable<System.DateTime> FechaTerminacion { get; set; }
        public string Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reclamaciones> Reclamaciones { get; set; }
    }
}
