//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjusteIPA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamaciones
    {
        public int idReclamacion { get; set; }
        public string NumReclamacion { get; set; }
        public Nullable<int> NumeroIPA { get; set; }
        public string NumeroPCP { get; set; }
        public string NombrePCP { get; set; }
        public Nullable<int> Tier { get; set; }
        public Nullable<int> Cuenta { get; set; }
        public string NumeroContrato { get; set; }
        public string NombreAsegurado { get; set; }
        public string Edad { get; set; }
        public Nullable<System.DateTime> FechaServicio { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<int> TipoServicio { get; set; }
        public string LugarServicio { get; set; }
        public string NumeroServicio { get; set; }
        public Nullable<double> CargoTotal { get; set; }
        public string ICD9 { get; set; }
        public string ICD10 { get; set; }
        public Nullable<int> IdCodigoCatastrofico { get; set; }
        public Nullable<int> Especialidad { get; set; }
        public Nullable<int> Municipio { get; set; }
        public Nullable<double> CantidadPagada { get; set; }
        public string EstatusAjuste { get; set; }
        public Nullable<double> CantidadAjustada { get; set; }
        public Nullable<System.DateTime> FechaAjuste { get; set; }
        public string EstatusReclamacion { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public string Comentarios { get; set; }
        public Nullable<bool> Seleccionar { get; set; }
    
        public virtual CodigoCatastrofico CodigoCatastrofico { get; set; }
        public virtual Cuenta Cuenta1 { get; set; }
        public virtual Especialidad Especialidad1 { get; set; }
        public virtual IPA IPA { get; set; }
        public virtual Municipio Municipio1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
