//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjusteIPA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroCatastrofico
    {
        public int idRegCatastrofico { get; set; }
        public string NumeroContrato { get; set; }
        public string NombreAsegurado { get; set; }
        public Nullable<int> IdCodigoCatastrofico { get; set; }
        public Nullable<System.DateTime> FechaComienzo { get; set; }
        public Nullable<System.DateTime> FechaTerminacion { get; set; }
    
        public virtual CodigoCatastrofico CodigoCatastrofico { get; set; }
    }
}
